/*
  # Add Reviews for Washington Venues

  1. Reviews
    - Add 3 specific, useful reviews for each venue
    - Reviews include venue-specific details and practical insights
    - Ratings range from 4-5 stars with constructive feedback
    - Automatically updates venue rating and review counts

  2. Security
    - Uses existing RLS policies on reviews table
*/

-- First, let's get the actual venue IDs and add reviews
DO $$
DECLARE
    venue_record RECORD;
    venue_ids UUID[];
BEGIN
    -- Get all venue IDs in order
    SELECT ARRAY(SELECT id FROM venues ORDER BY name) INTO venue_ids;
    
    -- Add reviews for each venue (3 reviews per venue)
    -- Venue 1: Fairmont Olympic Hotel
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[1], 'Catherine Lee', 5, 'Absolutely breathtaking venue for our art foundation gala! The Georgian Ballroom''s crystal chandeliers and marble columns created an elegant atmosphere that impressed all 200 guests. The staff was incredibly professional and handled our complex setup requirements flawlessly. Parking was convenient with valet service. Worth every penny for a high-end event.', '2024-04-28 19:30:00'),
    (venue_ids[1], 'Michael Rodriguez', 5, 'Hosted our company''s 50th anniversary celebration here and it exceeded expectations. The historic charm combined with modern amenities made it perfect for our multi-generational guest list. The catering team accommodated all dietary restrictions seamlessly. Only minor issue was the loading dock access for our AV equipment, but staff helped coordinate everything smoothly.', '2024-06-15 14:20:00'),
    (venue_ids[1], 'Jennifer Park', 4, 'Beautiful venue with impeccable service for our wedding reception. The ballroom''s acoustics were perfect for our live band. The coordinator was attentive to every detail. The only downside was the premium pricing, but the quality justified the cost. The historic Seattle location made for stunning photos. Highly recommend for upscale events.', '2024-08-03 16:45:00');

    -- Venue 2: Museum of Flight
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[2], 'David Thompson', 5, 'Incredible venue for our aerospace industry conference! Having presentations surrounded by historic aircraft created an inspiring atmosphere. The Great Gallery''s soaring ceilings and natural light were perfect for our 300 attendees. AV setup was seamless with their built-in systems. Parking was ample and the location near Boeing Field was convenient for our out-of-town guests.', '2024-03-12 10:15:00'),
    (venue_ids[2], 'Sarah Mitchell', 5, 'Unique and memorable venue for our son''s bar mitzvah! The kids were fascinated by the aircraft displays, and adults loved the sophisticated atmosphere. The catering space worked well for our kosher requirements. Staff was knowledgeable about both the venue and the exhibits. Great value for such a distinctive location. The photo opportunities were endless!', '2024-07-20 18:30:00'),
    (venue_ids[2], 'Robert Chen', 4, 'Fantastic venue for corporate events with a wow factor. The aviation theme perfectly matched our aerospace company''s brand. Setup was efficient with their experienced events team. Only challenge was managing guest flow around the exhibits during cocktail hour, but the staff provided good guidance. The venue''s educational aspect added value to our client appreciation event.', '2024-09-08 15:45:00');

    -- Venue 3: Chihuly Garden and Glass
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[3], 'Amanda Foster', 5, 'Absolutely magical venue for our intimate wedding! The glass art installations created the most romantic backdrop imaginable. The Garden room with its living ceiling was breathtaking for our ceremony. Staff was incredibly accommodating with our photography needs. The space feels much larger than expected and the lighting is perfect for evening events. Unforgettable experience!', '2024-05-18 19:00:00'),
    (venue_ids[3], 'James Wilson', 5, 'Hosted our art gallery''s donor appreciation event here - perfect match! The artistic environment inspired great conversations among our patrons. The unique setting made our event stand out from typical hotel venues. Catering presentation was elevated by the beautiful surroundings. Limited capacity actually worked in our favor for an exclusive feel. Highly recommend for arts organizations.', '2024-04-05 17:30:00'),
    (venue_ids[3], 'Lisa Zhang', 4, 'Stunning venue for our company''s creative team retreat. The artistic inspiration was exactly what we needed for our brainstorming sessions. The glass installations provided amazing conversation starters for networking. Space limitations required careful planning, but the intimate setting enhanced team bonding. Premium pricing but worth it for the unique experience and Seattle Center location.', '2024-06-22 14:15:00');

    -- Venue 4: Washington State Convention Center
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[4], 'Mark Johnson', 5, 'Perfect venue for our 1,500-person medical conference! The multiple breakout rooms allowed for concurrent sessions, and the main hall accommodated our keynote presentations beautifully. Loading dock access made vendor setup efficient. The downtown location was convenient for attendees staying at nearby hotels. Professional staff handled our complex AV requirements flawlessly. Great value for large-scale events.', '2024-02-14 09:30:00'),
    (venue_ids[4], 'Rachel Green', 4, 'Excellent facility for our trade show. The flexible space configuration allowed us to create distinct zones for exhibits, presentations, and networking. Parking can be challenging downtown, but the light rail access was convenient for many attendees. The venue''s technology infrastructure supported our digital displays perfectly. Staff was responsive to our changing needs throughout the event.', '2024-08-17 11:45:00'),
    (venue_ids[4], 'Thomas Lee', 5, 'Outstanding venue for our annual shareholders meeting. The professional atmosphere and state-of-the-art AV systems impressed our board members. The venue''s reputation added credibility to our event. Catering options were diverse and high-quality. The central Seattle location made it accessible for stakeholders from across the region. Highly recommend for corporate events requiring a prestigious setting.', '2024-10-03 13:20:00');

    -- Venue 5: Snoqualmie Falls
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[5], 'Emily Davis', 5, 'Absolutely breathtaking location for our outdoor wedding! The sound of the waterfall created natural ambiance that no DJ could match. The scenic beauty provided stunning photo opportunities throughout the day. Weather was a concern, but we had a backup plan and the natural setting was worth the risk. Parking was adequate and the short walk to the ceremony site added to the anticipation. Truly magical!', '2024-07-12 16:30:00'),
    (venue_ids[5], 'Kevin Martinez', 4, 'Incredible venue for our company retreat! The natural setting inspired creativity and team bonding in ways an indoor venue never could. The waterfall provided a powerful backdrop for our leadership presentations. Logistics required more planning than typical venues, but our event coordinator helped navigate the requirements. The unique setting made our retreat memorable and impactful.', '2024-05-25 12:00:00'),
    (venue_ids[5], 'Nicole Brown', 5, 'Perfect location for our environmental nonprofit''s fundraising gala! The natural beauty aligned perfectly with our mission and impressed our donors. The outdoor setting required weather contingencies, but the risk was worth the reward. The venue''s natural acoustics worked well for our speakers. Guests still talk about the stunning sunset ceremony. Highly recommend for organizations with environmental focus.', '2024-09-15 18:45:00');

    -- Continue with remaining venues...
    -- Venue 6: Pike Place Market
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[6], 'Daniel Kim', 4, 'Unique venue for our food industry networking event! The authentic market atmosphere created perfect ambiance for our culinary-focused gathering. The historic character and bustling energy made for great conversation starters. Logistics were challenging with limited loading access, but the venue''s charm made up for it. Great for events that want to showcase Seattle''s food culture. Parking required advance planning.', '2024-06-08 17:15:00'),
    (venue_ids[6], 'Michelle Taylor', 5, 'Fantastic location for our farm-to-table dinner series! The market setting perfectly complemented our local food theme. Vendors were accommodating and the historic atmosphere added authenticity to our event. The intimate space created great networking opportunities. Setup required coordination with market operations, but staff was helpful. Perfect for food-related events wanting genuine Seattle character.', '2024-08-30 19:30:00'),
    (venue_ids[6], 'Christopher Wang', 4, 'Great venue for our tourism board''s media event! The iconic Seattle location provided perfect photo opportunities for our promotional materials. The market''s energy and authenticity impressed our travel writers. Space limitations required creative planning, but the unique setting was worth the extra effort. Excellent for events wanting to showcase Seattle''s cultural identity.', '2024-04-20 14:45:00');

    -- Venue 7: Seattle Art Museum
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[7], 'Stephanie Adams', 5, 'Elegant venue for our cultural foundation''s annual gala! The museum''s sophisticated atmosphere elevated our fundraising event significantly. The art collections provided natural conversation pieces for our donors. Professional staff understood the needs of nonprofit events and provided excellent support. The downtown location was convenient for our attendees. Perfect blend of culture and class for upscale events.', '2024-03-22 18:00:00'),
    (venue_ids[7], 'Brian Cooper', 4, 'Impressive venue for our law firm''s client appreciation event! The refined atmosphere matched our professional image perfectly. The museum''s prestige added credibility to our gathering. Gallery spaces provided interesting backdrops for networking. Some restrictions on catering setup, but the venue''s elegance justified the constraints. Great for professional services firms wanting to impress clients.', '2024-09-12 17:30:00'),
    (venue_ids[7], 'Angela Rodriguez', 5, 'Beautiful venue for our art auction fundraiser! The museum setting was perfect for showcasing the donated artwork. The sophisticated environment attracted serious collectors and bidders. Staff was knowledgeable about both venue logistics and art handling requirements. The venue''s reputation helped legitimize our emerging artists. Excellent for arts-related fundraising events.', '2024-11-07 19:15:00');

    -- Venue 8: Space Needle
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[8], 'Gregory Hall', 5, 'Unforgettable venue for our company''s milestone celebration! The 360-degree city views created a spectacular backdrop for our achievement recognition event. The iconic location impressed our international clients and made the event truly memorable. Premium pricing was justified by the unique experience and prestige. Staff was professional and experienced with high-profile events. Perfect for once-in-a-lifetime celebrations.', '2024-05-10 20:00:00'),
    (venue_ids[8], 'Patricia Lewis', 4, 'Stunning venue for our wedding reception! The panoramic views of Seattle and the mountains created the most romantic setting imaginable. The space felt intimate despite being in such an iconic location. Weather wasn''t a concern with the enclosed observation deck. The venue''s fame added excitement for our out-of-town guests. Worth the premium for such a unique and memorable experience.', '2024-08-25 18:30:00'),
    (venue_ids[8], 'Jonathan Miller', 5, 'Incredible venue for our tech company''s product launch! The futuristic setting perfectly matched our innovative brand image. The Seattle skyline provided an inspiring backdrop for our presentations. The venue''s iconic status attracted media attention and enhanced our event''s profile. Logistics were handled professionally by experienced staff. Highly recommend for events wanting maximum impact and prestige.', '2024-07-03 16:45:00');

    -- Venue 9: Woodland Park Zoo
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[9], 'Rebecca Turner', 5, 'Amazing venue for our children''s charity fundraiser! The zoo setting delighted both kids and adults, creating a fun atmosphere that encouraged generous giving. The animal encounters added unique entertainment value that traditional venues can''t match. Staff was experienced with family-friendly events and handled logistics smoothly. Great outdoor spaces for activities. Perfect for family-oriented organizations and events.', '2024-06-18 15:30:00'),
    (venue_ids[9], 'Matthew Clark', 4, 'Unique venue for our environmental consulting firm''s team building event! The conservation theme aligned perfectly with our company values. The outdoor setting encouraged team bonding and creative thinking. Animal presentations provided natural icebreakers for networking. Some weather dependency, but the venue provided covered areas. Great for companies wanting to demonstrate environmental commitment.', '2024-04-15 13:45:00'),
    (venue_ids[9], 'Karen White', 5, 'Fantastic venue for our daughter''s sweet sixteen party! The zoo setting made it memorable and different from typical party venues. The kids loved the animal encounters, and parents appreciated the educational aspect. Staff was great with younger guests and handled the logistics of a large teen group well. Plenty of space for activities and the natural setting provided great photo opportunities.', '2024-09-28 14:20:00');

    -- Venue 10: Kerry Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[10], 'Steven Garcia', 4, 'Breathtaking location for our intimate wedding ceremony! The Seattle skyline and Mount Rainier views created the most romantic backdrop imaginable. The small space actually enhanced the intimate feel we wanted. Parking was limited, so we arranged shuttle service for guests. Weather was a concern, but we had backup plans. The iconic views made it worth the logistical challenges. Perfect for small, memorable ceremonies.', '2024-07-08 17:00:00'),
    (venue_ids[10], 'Diana Martinez', 5, 'Perfect spot for our photography club''s sunset gathering! The panoramic views provided endless opportunities for stunning shots. The elevated location offered perspectives you can''t get anywhere else in Seattle. Limited space meant we kept the group small, which enhanced the intimate workshop atmosphere. Free parking nearby was a bonus. Ideal for photography events and small artistic gatherings.', '2024-08-14 19:30:00'),
    (venue_ids[10], 'Robert Johnson', 4, 'Great location for our proposal! While not a large event, the setting was absolutely perfect for this special moment. The city lights and Space Needle view created a magical atmosphere. The small space meant privacy despite being a public location. Timing was important to avoid crowds, but early morning provided the perfect intimate setting. Highly recommend for romantic occasions and small celebrations.', '2024-05-22 06:30:00');

    -- Venue 11: Gasworks Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[11], 'Laura Thompson', 5, 'Fantastic venue for our company picnic! The large open spaces accommodated our 400 employees comfortably with room for games, food stations, and relaxation areas. The unique industrial sculptures provided interesting backdrops for team photos. Parking was ample and the lake views added to the atmosphere. Great facilities for large outdoor events. The quirky Seattle character made it memorable for our diverse workforce.', '2024-06-30 12:00:00'),
    (venue_ids[11], 'Charles Wilson', 4, 'Unique location for our art installation opening! The industrial aesthetic perfectly complemented our contemporary art pieces. The open space allowed for creative layout and good crowd flow. The park''s artistic character attracted the right audience for our event. Some wind challenges for displays, but the venue''s authenticity was worth the extra planning. Great for arts events wanting an unconventional setting.', '2024-09-05 18:15:00'),
    (venue_ids[11], 'Monica Davis', 5, 'Perfect venue for our family reunion! The large grassy areas gave kids plenty of space to play while adults could relax and catch up. The unique Seattle landmark made it special for our out-of-town relatives. Picnic facilities were adequate and the views were beautiful. Free parking was a huge advantage for a large family gathering. Highly recommend for casual, large group events.', '2024-08-12 14:30:00');

    -- Venue 12: Discovery Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[12], 'Paul Anderson', 5, 'Beautiful venue for our nature conservation fundraiser! The old-growth forest setting perfectly aligned with our environmental mission. The diverse ecosystems provided natural education opportunities for our guests. Trails accommodated our guided walk activities well. The Puget Sound views from the bluffs were spectacular for our sunset reception. Perfect for environmental organizations and nature-focused events.', '2024-05-28 16:45:00'),
    (venue_ids[12], 'Jennifer Lee', 4, 'Great location for our corporate wellness retreat! The natural setting encouraged mindfulness and stress relief for our team. Multiple trail options accommodated different fitness levels. The beach access provided unique team building opportunities. Some logistics challenges with equipment transport, but the venue''s therapeutic benefits were worth it. Excellent for companies prioritizing employee wellness.', '2024-07-16 10:30:00'),
    (venue_ids[12], 'Michael Brown', 5, 'Incredible venue for our outdoor wedding! The lighthouse and Sound views created the most romantic Pacific Northwest setting. The meadow ceremony site was perfect for our 150 guests. Multiple photo locations throughout the park gave us amazing variety. Weather backup required planning, but the natural beauty was worth the risk. Highly recommend for couples wanting authentic Northwest outdoor weddings.', '2024-09-18 15:00:00');

    -- Venue 13: Alki Beach
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[13], 'Sandra Miller', 5, 'Perfect beach venue for our summer company party! The sandy beach and Seattle skyline views created an amazing atmosphere for our team celebration. Beach volleyball and water activities kept everyone engaged. The 2.5-mile stretch provided plenty of space for our 200 employees. Parking along the beach was convenient. Great for casual, fun corporate events with a relaxed vibe.', '2024-07-22 17:30:00'),
    (venue_ids[13], 'David Rodriguez', 4, 'Beautiful location for our beach wedding ceremony! The Sound views and city skyline created a stunning backdrop. The sandy beach was perfect for our barefoot ceremony. Sunset timing made for incredible photos. Wind was a factor for decorations, but added to the authentic beach experience. Limited facilities required extra planning, but the natural beauty made it worthwhile. Great for casual, romantic weddings.', '2024-08-19 18:45:00'),
    (venue_ids[13], 'Lisa Garcia', 5, 'Fantastic venue for our charity beach cleanup and celebration! The beach setting perfectly matched our environmental mission. The long shoreline accommodated our 300 volunteers for cleanup activities. The celebration afterward with skyline views was inspiring for our cause. Great community visibility for our nonprofit. Perfect for environmental organizations and community service events.', '2024-06-25 14:15:00');

    -- Venue 14: Green Lake Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[14], 'Timothy Wilson', 5, 'Excellent venue for our running club''s annual celebration! The 2.8-mile loop was perfect for our fun run event, and the park facilities accommodated our post-race gathering beautifully. The lake views provided a scenic backdrop for awards and socializing. Ample parking and good accessibility for all ages. The community center facilities were helpful for registration and refreshments. Perfect for active lifestyle events.', '2024-05-14 11:00:00'),
    (venue_ids[14], 'Michelle Taylor', 4, 'Great location for our family''s large reunion picnic! The open spaces accommodated our 80+ family members with room for games, food, and relaxation. The playground kept the kids entertained while adults caught up. Lake activities added fun for the adventurous family members. Parking filled up quickly on weekends, so we arrived early. Excellent for large family gatherings and casual celebrations.', '2024-08-06 13:30:00'),
    (venue_ids[14], 'Christopher Lee', 5, 'Perfect venue for our wellness company''s outdoor yoga retreat! The peaceful lake setting created ideal ambiance for mindfulness activities. Multiple grassy areas allowed for different class sizes and activities. The walking path provided options for moving meditation. Easy access and parking made it convenient for participants. Great for wellness events and outdoor fitness activities.', '2024-06-12 08:45:00');

    -- Venue 15: Lincoln Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[15], 'Amanda Foster', 5, 'Beautiful venue for our community festival! The large open spaces accommodated multiple activity areas, food vendors, and entertainment stages. The Sound views added to the festive atmosphere. Great facilities including restrooms and covered areas. The diverse landscapes provided variety for different activities. Excellent parking and accessibility. Perfect for community events and large outdoor celebrations.', '2024-07-04 15:20:00'),
    (venue_ids[15], 'James Clark', 4, 'Great location for our corporate team building retreat! The variety of outdoor spaces allowed for different activities and breakout sessions. The beach access provided unique team challenges and bonding opportunities. The park''s natural beauty inspired creativity and collaboration. Some wind challenges near the water, but multiple sheltered areas were available. Excellent for companies wanting outdoor team development.', '2024-09-22 12:15:00'),
    (venue_ids[15], 'Rachel Green', 5, 'Fantastic venue for our daughter''s graduation party! The combination of open spaces, beach access, and beautiful views made it perfect for our celebration. Kids enjoyed the playground while adults relaxed with Sound views. The variety of settings provided great photo opportunities. Ample parking was a huge advantage for our large guest list. Highly recommend for milestone celebrations and family events.', '2024-06-18 16:00:00');

    -- Venue 16: Volunteer Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[16], 'Nicole Brown', 5, 'Elegant venue for our garden party fundraiser! The conservatory and formal gardens created a sophisticated atmosphere perfect for our donor cultivation event. The historic character and beautiful landscaping impressed our guests. Multiple garden areas provided variety for cocktails and presentations. The venue''s prestige enhanced our organization''s image. Perfect for upscale outdoor events and nonprofit fundraisers.', '2024-05-20 17:45:00'),
    (venue_ids[16], 'Daniel Kim', 4, 'Beautiful location for our wedding photos and small ceremony! The conservatory provided stunning backdrops and the gardens offered variety for different shots. The historic water tower area was unique and memorable. Limited parking required guest coordination, but the beauty was worth the logistics. The intimate scale worked perfectly for our small wedding. Great for couples wanting elegant, historic Seattle charm.', '2024-08-28 14:30:00'),
    (venue_ids[16], 'Michelle Rodriguez', 5, 'Perfect venue for our horticultural society''s annual meeting! The conservatory and gardens provided natural education opportunities and inspiration for our members. The historic setting added gravitas to our presentations. Beautiful spaces for both formal sessions and informal networking. The venue''s botanical focus perfectly matched our organization''s mission. Excellent for garden clubs and environmental groups.', '2024-04-10 13:00:00');

    -- Venue 17: Myrtle Edwards Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[17], 'Kevin Martinez', 5, 'Spectacular venue for our waterfront corporate event! The Elliott Bay views and Olympic Mountains backdrop created an inspiring setting for our leadership retreat. The 1.25-mile waterfront path was perfect for walking meetings and team building activities. Easy downtown access made it convenient for our urban-based team. The combination of city proximity and natural beauty was ideal for our professional event.', '2024-06-02 16:15:00'),
    (venue_ids[17], 'Sarah Johnson', 4, 'Great location for our cycling club''s season kickoff! The flat, paved path was perfect for our group ride, and the waterfront setting made for beautiful scenery. The park facilities accommodated our post-ride gathering well. Parking was adequate and the downtown location was convenient for members. Some wind off the water, but the views made up for it. Perfect for active groups and fitness events.', '2024-04-25 10:45:00'),
    (venue_ids[17], 'Thomas Anderson', 5, 'Beautiful venue for our maritime industry networking event! The waterfront setting perfectly matched our industry focus and provided natural conversation starters. The Sound views and shipping activity created authentic maritime atmosphere. Easy access for downtown professionals and great visibility for our organization. The linear park layout worked well for our walking networking format. Excellent for industry-specific events.', '2024-09-14 18:00:00');

    -- Venue 18: Golden Gardens Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[18], 'Emily Davis', 5, 'Absolutely perfect venue for our beach wedding! The sandy beach ceremony with Puget Sound and Olympic Mountains views was breathtaking. The sunset timing created magical lighting for photos. Beach bonfire reception was unique and memorable for our guests. The natural amphitheater setting worked beautifully for our vows. Weather backup required planning, but the stunning location was worth any risk. Highly recommend for romantic beach weddings.', '2024-07-30 19:00:00'),
    (venue_ids[18], 'Mark Thompson', 4, 'Great venue for our summer company barbecue! The beach setting created a relaxed, fun atmosphere for our team celebration. Beach activities and volleyball kept everyone engaged. The fire pits were perfect for evening socializing. Parking filled up quickly, so we arranged carpools. The natural beauty and casual vibe made it memorable for our diverse workforce. Excellent for informal corporate events.', '2024-08-15 17:30:00'),
    (venue_ids[18], 'Jennifer Wilson', 5, 'Fantastic location for our environmental group''s beach cleanup and celebration! The beautiful beach setting motivated our volunteers and provided great visibility for our cause. The post-cleanup celebration with sunset views was inspiring and rewarding. Great community engagement and media opportunities. The venue''s natural beauty reinforced our conservation message. Perfect for environmental organizations and community service events.', '2024-06-20 15:45:00');

    -- Venue 19: Carkeek Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[19], 'Robert Chen', 5, 'Incredible venue for our nature education nonprofit''s fundraiser! The old-growth forest and salmon viewing area perfectly aligned with our environmental mission. The diverse ecosystems provided natural education opportunities for our donors. The beach access added variety to our event activities. Great facilities and the authentic Pacific Northwest setting impressed our supporters. Perfect for environmental organizations and educational events.', '2024-05-12 14:20:00'),
    (venue_ids[19], 'Lisa Zhang', 4, 'Beautiful location for our family''s outdoor wedding! The forest ceremony site was magical and intimate. The creek sounds provided natural ambiance that enhanced our vows. Multiple photo locations throughout the park gave us amazing variety. The beach reception area was unique and memorable. Some logistics challenges with equipment access, but the natural beauty made it worthwhile. Great for couples wanting authentic Northwest outdoor weddings.', '2024-09-10 16:30:00'),
    (venue_ids[19], 'Christopher Wang', 5, 'Perfect venue for our corporate sustainability retreat! The forest setting inspired environmental thinking and team bonding. The salmon habitat demonstrations aligned with our company''s conservation initiatives. Multiple trail options accommodated different activities and group sizes. The authentic wilderness experience was refreshing for our urban-based team. Excellent for companies emphasizing environmental responsibility.', '2024-07-18 11:15:00');

    -- Venue 20: Seward Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[20], 'Angela Rodriguez', 5, 'Amazing venue for our community cultural festival! The large open spaces accommodated multiple performance stages, food vendors, and activity areas. The lake views and old-growth forest provided beautiful backdrops. Great facilities including covered areas and restrooms. The 2.4-mile loop trail offered additional activities for guests. Excellent parking and accessibility. Perfect for large community events and cultural celebrations.', '2024-08-21 13:45:00'),
    (venue_ids[20], 'Brian Cooper', 4, 'Great location for our corporate wellness day! The combination of forest trails and lakefront areas provided variety for different wellness activities. The peaceful setting encouraged mindfulness and stress relief. Multiple spaces allowed for concurrent sessions and activities. Some parking challenges during peak times, but the venue''s therapeutic benefits were worth it. Excellent for employee wellness programs and health-focused events.', '2024-06-08 09:30:00'),
    (venue_ids[20], 'Stephanie Adams', 5, 'Beautiful venue for our extended family reunion! The large picnic areas accommodated our 100+ family members comfortably. The playground and beach access kept kids entertained while adults relaxed. The walking trail provided activities for all ages and fitness levels. Great photo opportunities throughout the park. The peaceful lake setting made it special for our multi-generational gathering. Highly recommend for large family events.', '2024-07-26 12:45:00');

    -- Venue 21: Magnuson Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[21], 'Gregory Hall', 5, 'Fantastic venue for our large corporate picnic! The 350-acre space easily accommodated our 500 employees with room for sports, games, and relaxation areas. The off-leash dog area was a hit with pet-owning employees. Lake Washington access provided water activities and beautiful views. Excellent facilities and ample parking. The variety of spaces allowed for different activities simultaneously. Perfect for large-scale corporate events.', '2024-06-15 14:00:00'),
    (venue_ids[21], 'Patricia Lewis', 4, 'Great location for our dog rescue organization''s adoption event! The off-leash area was perfect for potential adopters to interact with dogs in a natural setting. The large open spaces accommodated our booths, demonstrations, and activities. Great visibility and community access for our cause. Ample parking was essential for our large volunteer team. The dog-friendly environment perfectly matched our mission. Excellent for pet-related organizations and events.', '2024-05-30 11:30:00'),
    (venue_ids[21], 'Jonathan Miller', 5, 'Perfect venue for our youth sports league''s championship tournament! The multiple fields and open spaces allowed for concurrent games and activities. Great facilities for teams, families, and spectators. The lakefront location provided beautiful views and additional activities. Excellent parking and accessibility for our large tournament. The variety of spaces accommodated different age groups and activities. Highly recommend for sports organizations and youth events.', '2024-08-07 10:15:00');

    -- Venue 22: Washington Park Arboretum
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[22], 'Rebecca Turner', 5, 'Absolutely beautiful venue for our botanical society''s annual gala! The diverse plant collections and seasonal blooms created stunning natural decorations. The Japanese Garden was particularly magical for our cocktail reception. The educational aspect added value for our members and guests. Professional staff understood the needs of horticultural events. The venue''s prestige enhanced our organization''s fundraising efforts. Perfect for garden clubs and environmental organizations.', '2024-04-28 17:00:00'),
    (venue_ids[22], 'Matthew Clark', 4, 'Gorgeous location for our intimate wedding ceremony! The Japanese Garden provided the most serene and beautiful setting for our vows. The variety of garden settings offered amazing photo opportunities throughout the seasons. Limited capacity actually enhanced the intimate feel we wanted. Some restrictions on decorations to protect the plants, but the natural beauty needed no enhancement. Great for couples wanting elegant, natural wedding settings.', '2024-10-12 15:30:00'),
    (venue_ids[22], 'Karen White', 5, 'Perfect venue for our environmental education nonprofit''s donor appreciation event! The arboretum setting perfectly aligned with our mission and provided natural education opportunities. The diverse ecosystems sparked great conversations among our supporters. The peaceful environment encouraged meaningful connections and generous giving. Great for organizations focused on conservation, education, and environmental stewardship.', '2024-06-05 16:45:00');

    -- Venue 23: Kubota Garden
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[23], 'Steven Garcia', 5, 'Breathtaking venue for our Japanese cultural organization''s tea ceremony event! The authentic Japanese garden design created perfect ambiance for our traditional celebration. The peaceful water features and carefully designed landscapes provided ideal settings for meditation and reflection. The venue''s cultural significance added depth to our event. Limited capacity enhanced the intimate, authentic experience. Perfect for cultural organizations and traditional ceremonies.', '2024-05-18 14:15:00'),
    (venue_ids[23], 'Diana Martinez', 4, 'Beautiful location for our small wedding ceremony! The Japanese garden aesthetics created the most peaceful and romantic setting. The stone lanterns and water features provided unique photo opportunities. The intimate scale was perfect for our small guest list. Some seasonal considerations for plant blooms, but each season offered different beauty. The authentic design and tranquil atmosphere made our ceremony truly special. Great for intimate, culturally-inspired weddings.', '2024-09-25 16:00:00'),
    (venue_ids[23], 'Robert Johnson', 5, 'Incredible venue for our mindfulness retreat! The Japanese garden design principles created ideal environments for meditation and reflection. The carefully planned sight lines and peaceful water sounds enhanced our contemplative activities. The authentic cultural elements added educational value to our program. Perfect for wellness organizations, meditation groups, and spiritual retreats seeking authentic, peaceful settings.', '2024-07-14 10:30:00');

    -- Venue 24: Schmitz Preserve Park
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[24], 'Laura Thompson', 5, 'Amazing venue for our environmental education group''s old-growth forest workshop! The pristine old-growth ecosystem provided unparalleled educational opportunities about Pacific Northwest forests. The cathedral-like atmosphere of the ancient trees created a sense of reverence and wonder. Perfect for small groups wanting authentic wilderness education. The preserve''s ecological significance added weight to our conservation message. Excellent for environmental organizations and nature education.', '2024-04-22 13:30:00'),
    (venue_ids[24], 'Charles Wilson', 4, 'Unique location for our intimate wedding ceremony! The old-growth forest created the most magical and spiritual setting for our vows. The ancient trees provided natural cathedral architecture that no building could match. The small scale was perfect for our intimate guest list. Limited access required careful planning, but the pristine natural beauty was worth the logistics. Great for couples wanting authentic, spiritual outdoor ceremonies.', '2024-08-12 17:15:00'),
    (venue_ids[24], 'Monica Davis', 5, 'Perfect venue for our forest therapy and wellness retreat! The old-growth ecosystem provided ideal conditions for nature-based healing and mindfulness practices. The pristine environment enhanced our participants'' connection with nature. The scientific and spiritual significance of the preserve added depth to our program. Excellent for wellness practitioners and organizations focused on nature-based healing and environmental connection.', '2024-06-28 11:45:00');

    -- Venue 25: Fremont Troll
    INSERT INTO reviews (venue_id, user_name, rating, comment, created_at) VALUES
    (venue_ids[25], 'Paul Anderson', 4, 'Quirky and memorable venue for our art collective''s guerrilla exhibition! The troll sculpture provided an iconic Seattle backdrop that perfectly matched our unconventional art style. The unique location attracted curious passersby and created great community engagement. Limited space required creative planning, but the venue''s character was worth the constraints. Great for arts events wanting authentic Seattle weirdness and community visibility.', '2024-05-08 18:30:00'),
    (venue_ids[25], 'Jennifer Lee', 5, 'Fun and unique location for our photography club''s urban exploration workshop! The troll sculpture and bridge architecture provided fascinating subjects for creative photography. The iconic Seattle landmark attracted both locals and tourists, creating dynamic shooting opportunities. The quirky character perfectly represented Seattle''s artistic spirit. Perfect for photography groups and creative organizations wanting distinctive, Instagram-worthy locations.', '2024-07-20 15:45:00'),
    (venue_ids[25], 'Michael Brown', 4, 'Memorable venue for our small, unconventional wedding ceremony! The troll sculpture created a uniquely Seattle backdrop that reflected our quirky personalities. The intimate space was perfect for our small guest list of fellow artists and creatives. The location''s fame provided great conversation starters and photo opportunities. Great for couples wanting non-traditional, authentically Seattle wedding experiences that reflect the city''s creative spirit.', '2024-09-03 16:20:00');

END $$;

-- Update venue ratings and review counts based on the new reviews
UPDATE venues SET 
  rating = (
    SELECT ROUND(AVG(rating::numeric), 2)
    FROM reviews 
    WHERE reviews.venue_id = venues.id
  ),
  reviews_count = (
    SELECT COUNT(*)
    FROM reviews 
    WHERE reviews.venue_id = venues.id
  )
WHERE id IN (
  SELECT DISTINCT venue_id FROM reviews
);